# Generated by Django 5.1.7 on 2025-03-24 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(max_length=250)),
                ('date', models.DateField(verbose_name='Due date')),
                ('priority', models.CharField(choices=[('A', 'low'), ('B', 'normal'), ('C', 'urgent')], default='A', max_length=1)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.employee')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
